version: '3.5'
services:

  user-db:
    container_name: user-db
    build: postgresql
    image: taskmanager_user_db
    hostname: ${USER_DB_HOST}
    restart: always
    environment:
      POSTGRES_DB: ${USER_POSTGRES_DB}
      POSTGRES_USER: ${USER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${USER_POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data/user-service:/var/lib/postgresql/data
    networks:
      - taskmanager_ntwrks

  task-db:
    container_name: task-db
    build: postgresql
    image: taskmanager_task_db
    hostname: ${TASK_DB_HOST}
    restart: always
    environment:
      POSTGRES_DB: ${TASK_POSTGRES_DB}
      POSTGRES_USER: ${TASK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TASK_POSTGRES_PASSWORD}
    ports:
      - '5434:5432'
    volumes:
      - ./postgres-data/task-service:/var/lib/postgresql/data
    networks:
      - taskmanager_ntwrks

  audit-db:
    container_name: audit-db
    build: postgresql
    image: taskmanager_audit_db
    hostname: ${AUDIT_DB_HOST}
    restart: always
    environment:
      POSTGRES_DB: ${AUDIT_POSTGRES_DB}
      POSTGRES_USER: ${AUDIT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUDIT_POSTGRES_PASSWORD}
    ports:
      - '5433:5432'
    volumes:
      - ./postgres-data/audit-service:/var/lib/postgresql/data
    networks:
      - taskmanager_ntwrks
      
  pgadmin:
    container_name: pgadmin
    build: pgadmin
    image: taskmanager_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.admin
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "82:80"
    networks:
      - taskmanager_ntwrks

  user-service:
    container_name: user-service
    build: user-service
    image: taskmanager_user-service
    restart: always
    env_file:
      - .env
    networks:
      - taskmanager_ntwrks

  task-service:
    container_name: task-service
    build: task-service
    image: taskmanager_task-service
    restart: always
    env_file:
      - .env
    networks:
      - taskmanager_ntwrks

  audit-service:
     container_name: audit-service
     build: audit-service
     image: taskmanager_audit-service
     restart: always
     env_file:
       - .env
     networks:
       - taskmanager_ntwrks

  swagger-ui:
    container_name: swagger-ui
    build: swagger-ui
    image: taskmanager_swagger-ui
    ports:
      - "81:8080"
    networks:
      - taskmanager_ntwrks

  proxy:
    container_name: proxy
    build: proxy
    image: taskmanager_proxy
    ports:
      - "80:80"
    networks:
      - taskmanager_ntwrks
networks:
  taskmanager_ntwrks:
    name: taskmanager_ntwrks