spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/audit_service?ApplicationName=Audit_Service
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate.default_schema: app

#    hibernate:
#      ddl-auto: create

server:
  port: 8081

app:
  user-url: http://localhost:8080/users