spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AddRequestHeader=X-Checker, check
            - StripPrefix=2

        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/api/v1/task/**, /api/v1/project/**
          filters:
            - AddRequestHeader=X-Checker, check
            - StripPrefix=2

        - id: audit-service
          uri: lb://audit-service
          predicates:
            - Path=/api/v1/audit/**
          filters:
            - AddRequestHeader=X-Checker, check
            - StripPrefix=2

# Server
server:
  port: ${SERVICE_PORT:8083}

#Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761}/eureka
  instance:
    preferIpAddress: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /api/v1/audit/v3/api-docs
        name: Audit Service
      - url: /api/v1/users/v3/api-docs
        name: User Service
      - url: /api/v1/task/v3/api-docs
        name: Task Service


# Debug
logging:
  level:
    web: DEBUG
