spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AddRequestHeader=X-Checker, check
            - StripPrefix=2

        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/api/v1/task/**, /api/v1/project/**
          filters:
            - AddRequestHeader=X-Checker, check
            - StripPrefix=2

        - id: audit-service
          uri: lb://audit-service
          predicates:
            - Path=/api/v1/audit/**
          filters:
            - AddRequestHeader=X-Checker, check
            - StripPrefix=2

# Server
server:
  port: ${SERVICE_PORT:8083}

# Debug
logging:
  level:
    web: DEBUG
