spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_service?ApplicationName=User_Service
    username: postgres
    password: postgres
    hikari:
      schema: app
  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    open-in-view: true
#    hibernate:
#      ddl-auto: create

#  config:
#    import: confidential.yml

logging:
  level:
    org:
      hibernate:
        SQL:
          DEBUG
        orm:
          jdbc:
            bind:
              Trace

server:
  port: 8080
 