spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service?ApplicationName=User_Service
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate.default_schema: app

#    hibernate:
#      ddl-auto: create

app:
  user-verification-path: http://localhost:8080/users/verification
  audit-url: http://localhost:8081/audit

