spring:
  application:
    name: user-service
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate.default_schema: users
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://user-db:5432/user-service
    username: root
    password: root

  jackson:
    property-naming-strategy: SNAKE_CASE

  config:
    import: confidential.yml

logging:
  level:
    org:
      hibernate:
        SQL:
          DEBUG
        orm:
          jdbc:
            bind:
              Trace

server:
  port: 8080

app:
  user-verification-path: http://localhost/api/v1/users/verification
  audit-url: http://audit-service:8080/audit