spring:
  application:
    name: task-service
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate.default_schema: task
#    hibernate:
#      ddl-auto: create

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://task-db:5432/task-service
    username: root
    password: root

  config:
    import: confidential.yml

logging:
  level:
    org:
      hibernate:
        SQL:
          DEBUG
        orm:
          jdbc:
            bind:
              Trace

server:
  port: 8080

app:
  user-url: http://user-service:8080/users
  audit-url: http://audit-service:8080/audit