spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/task_service
    username: postgres
    password: postgres

#  jpa:
#    hibernate:
#      ddl-auto: update

server:
  port: 8082

app:
  user-url: http://localhost:8080/users
  audit-url: http://localhost:8081/audit