#Stpring
spring:
  application:
    name: task-service

#Jpa
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate.default_schema: ${DEFAULT_SCHEMA:app}

#Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${TASK_DB_HOST:localhost}:${DB_POST:5434}/${TASK_POSTGRES_DB:task-service}
    username: ${TASK_POSTGRES_USER:root}
    password: ${TASK_POSTGRES_PASSWORD:root}

#Flyway
  flyway:
    schemas: ${FLYWAY_SCHEMA:flyway}

#Jackson
  jackson:
    property-naming-strategy: SNAKE_CASE

#Config
  config:
    import: confidential.yml

#Cloud
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          audit-service:
            defaultRequestHeaders:
              X-Checker: check
            logger-level: full
          user-service:
            defaultRequestHeaders:
              X-Checker: check
            logger-level: full
#      micrometer:
#        enabled: true

#Resilience4j
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        waitDurationInOpenState: 45s
        permittedNumberOfCallsInHalfOpenState: 13
        minimumNumberOfCalls: 2
        failureRateThreshold: 35
  timelimiter:
    configs:
      default:
        timeoutDuration: 10s

#Logging
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  file:
    name: task-service/logs/${spring.application.name}.log
  logback:
    rolling-policy:
      max-file-size: 1MB
      file-name-pattern: logs/${spring.application.name}.%d{yyyy.MM.dd}.%i.log
      max-history: 7

#Server
server:
  port: ${SERVICE_PORT:8082}

#Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761}/eureka
  instance:
    preferIpAddress: true

#SpringDoc
springdoc:
  api-docs:
    path: /task/v3/api-docs
  swagger-ui:
    path: /task/swagger-ui.html

